# Generated by Django 4.1.4 on 2023-01-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show1', '0004_alter_movieshow_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshow',
            name='time',
            field=models.CharField(choices=[('6:30 AM', '6:30 AM'), ('10:30 AM', '10:30 AM'), ('2:30 PM', '2:30 PM'), ('6:30 PM', '6:30 PM'), ('10:30 PM', '10:30 PM')], max_length=100, null=True),
        ),
    ]
