# Generated by Django 4.1.4 on 2023-02-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show1', '0006_remove_seats_seatname_seats_seatalp_seats_seatnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='seatalp',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='seats',
            name='seatnum',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
    ]
