# Generated by Django 4.1.4 on 2022-12-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='location',
            field=models.CharField(choices=[('Trivandrum', 'Trivandrum'), ('Eranakulam', 'Eranakulam')], max_length=50, null=True),
        ),
    ]
